# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Redirectway"
client_id = "9490ee4275141832d886b0ec306c6c94"
application_url = "https://longest-agreements-burden-viii.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://longest-agreements-burden-viii.trycloudflare.com/auth/callback",
  "https://longest-agreements-burden-viii.trycloudflare.com/auth/shopify/callback",
  "https://longest-agreements-burden-viii.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "techtcl-pointer.myshopify.com"
